name: Wormhole
version: 1.4.0
author: Austin Bowen <austin.bowen.314@gmail.com>
main: info.saltyhash.plugin.Wormhole
softdepend: [Vault]
commands:
  plugin:
    description: Display all Wormhole commands
    aliases: [worm]
    usage: /<command> [add | back | cost | del | jump | list | rename | replace | set | unset]
  plugin reload:
    description: Reload config
    usage: /<command>
  plugin version:
    description: Display the Wormhole version
    usage: /<command>
  worm add:
    description: Create a new jump
    usage: /<command> [player | pub] <jump name>
  worm back:
    description: Jump back to previous location
    usage: /<command>
  worm cost:
    description: Displays the cost of all actions
    usage: /<command>
  worm del:
    description: Delete a jump
    usage: /<command> [player | pub] <jump name>
  worm jump:
    description: Jump directly to a jump
    usage: /<command> [player | pub] <jump name>
  worm list:
    description: List Jumps
    usage: /<command> [player | pub] [page]
  worm rename:
    description: Rename a Jump
    usage: /<command> [player | pub] <old name> <new name>
  worm replace:
    description: Replace an existing Jump with the current location
    usage: /<command> [player | pub] <jump name>
  worm set:
    description: Set a sign to point to a Jump
    usage: /<command> [player | pub] <jump name>
  worm unset:
    description: Unset a sign pointing to a Jump
    usage: /<command>
permissions:
  plugin.*:
    description: Gives all permissions for Wormhole
    default: op
    children:
      plugin.add.*:
        description: Create / replace all types of Jump
        children:
          plugin.add.other:
            description: Create private Jumps for other players
            default: op
          plugin.add.private:
            description: Create private Jumps
            default: true
          plugin.add.public:
            description: Create public Jumps
            default: op
      plugin.back:
        description: Jump back to previous location
        default: true
      plugin.del.*:
        description: Delete all types of Jump
        children:
          plugin.del.other:
            description: Delete other users' Jumps
            default: op
          plugin.del.private:
            description: Delete private Jumps
            default: true
          plugin.del.public:
            description: Delete public Jumps
            default: op
      plugin.free:
        description: Exept from being charged to use Wormhole
        default: op
      plugin.jump.*:
        description: Jump directly to any type of Jump
        children:
          plugin.jump.other:
            description: Jump directly to another user's Jump
            default: op
          plugin.jump.private:
            description: Jump directly to private Jump
            default: true
          plugin.jump.public:
            description: Jump directly to public Jump
            default: true
      plugin.list.*:
        description: List all types of Jump
        children:
          plugin.list.other:
            description: List others' Jumps
            default: op
          plugin.list.private:
            description: List private Jumps
            default: true
          plugin.list.public:
            description: List public Jumps
            default: true
      plugin.reload:
        description: Reload config
        default: op
      plugin.rename:
        description: Rename all types of Jump
        children:
          plugin.rename.other:
            description: Rename other players' Jumps
            default: op
          plugin.rename.private:
            description: Rename private Jumps
            default: true
          plugin.rename.public:
            description: Rename public Jumps
            default: op
      plugin.replace.*:
        description: Replace all types of Jump
        children:
          plugin.replace.other:
            description: Replace other players' Jumps
            default: op
          plugin.replace.private:
            description: Replace private Jumps
            default: true
          plugin.replace.public:
            description: Replace public Jumps
            default: op
      plugin.set.*:
        description: Set sign to point to all types of Jump
        children:
          plugin.set.other:
            description: Set sign to point to another user's Jump
            default: op
          plugin.set.private:
            description: Set sign to point to a private Jump
            default: true
          plugin.set.public:
            description: Set sign to point to a public Jump
            default: op
      plugin.unset.*:
        description: Unset sign pointing to any type of Jump
        children:
          plugin.unset.other:
            description: Unset sign pointing to another user's Jump
            default: op
          plugin.unset.private:
            description: Unset sign pointing to private Jump
            default: true
          plugin.unset.public:
            description: Unset sign pointing to public Jump
            default: op
      plugin.use.*:
        description: Use sign pointing to any type of Jump
        children:
          plugin.use.other:
            description: Use another user's Jump sign
            default: op
          plugin.use.private:
            description: Use private Jump sign
            default: true
          plugin.use.public:
            description: Use public Jump sign
            default: true
      plugin.version:
        description: Display the Wormhole version
        default: op